config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'splash#index'

  resources :groups, only: [:index, :new, :show, :create]
  resources :entities, only: [:new, :show, :create]

  get 'completed', to: 'entities#completed'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Group, author: user
    can :manage, Entity, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :groups, foreign_key: 'author_id'
  has_many :entities, foreign_key: 'author_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @entity = Entity.new
  end

  def create
    @entity = current_user.entities.new(entity_params)

    if @entity.save
      @group_entity = @entity.group_entities.create(group_entity_params)
      redirect_to group_path(@group_entity.group_id), notice: 'Transaction successful'
    else
      flash[:alert] = @entity.errors.full_messages.first
      render :new
    end
  end

  def completed; end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end

  def group_entity_params
    params.require(:entity).permit(:group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @groups = current_user.groups.includes(group_entities: :entity)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @group_entities = GroupEntity.includes(:group, :entity).where(group_id: params[:id]).order(created_at: :desc)
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'New category added successfully'
    else
      flash[:alert] = @group.errors.full_messages.first
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/entities/_form.html.erb
<%= form_with model: @entity do |f| %>
  <div class="field">
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>

  <div class="field">
    <%= f.text_field :amount, placeholder: 'Amount (USD)' %>
  </div>

  <div class="select-field">
    <%= f.label :group_id, 'Category' %>
    <%= f.collection_select :group_id, current_user.groups, :id, :name %>
  </div>

  <div class="button-container">
    <%= f.submit 'Create transaction', class: 'second-button' %>
  </div>
<% end %>

app/views/entities/new.html.erb
<header class="app-header">
  <%= link_to fa_icon('arrow-left'), :back, class: 'back-arrow' %>

  <h1 class="page-title">TRANSACTIONS</h1>

  <p class="header-link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></p>
</header>

<%= render 'form' %>

app/views/groups/_form.html.erb
<%= form_with model: @group do |f| %>
  <div class="field">
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>

  <div class="field">
    <%= f.text_field :icon, placeholder: 'Icon URL' %>
  </div>

  <div class="button-container">
    <%= f.submit 'Create category',class: 'second-button' %>
  </div>
<% end %>

app/views/groups/index.html.erb
<header class="app-header">
  <%= link_to fa_icon('arrow-left'), root_path, class: 'back-arrow' %>

  <h1 class="page-title">CATEGORIES</h1>

  <p class="header-link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></p>
</header>
<% if @groups.empty? %>
  <h2 class="splash-welcome">There are not categories yet!</h2>
  <p class="splash-text">Create your first category by clicking on the button below.</p>
<% else %>
  <ul class="groups-list">
    <% @groups.each do |group| %>
      <li class="groups-list-item">
        <img src="<%= group.icon %>" alt="Category icon image">
        <div class="group-info">
          <h2><%= group.name %></h2>
          <p><%= link_to 'View transactions', group_path(group.id) %></p>
        </div>
        <% total = 0.00 %>
        <% group.group_entities.each {|group_entity| total += group_entity.entity.amount} %>
        <span class="amount">$<%= total %></span>
      </li>
    <% end %>
  </ul>
<% end %>
<div class="button-container">
  <%= button_to 'New Category', new_group_path, method: :get, class: 'second-button' %>
</div>

app/views/groups/new.html.erb
<header class="app-header">
  <%= link_to fa_icon('arrow-left'), groups_path, class: 'back-arrow' %>

  <h1 class="page-title">CATEGORIES</h1>

  <p class="header-link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></p>
</header>
<%= render 'form' %>

app/views/groups/show.html.erb
<header class="app-header">
  <%= link_to fa_icon('arrow-left'), groups_path, class: 'back-arrow' %>

  <h1 class="page-title">TRANSACTIONS</h1>

  <p class="header-link"><%= link_to "Log out", destroy_user_session_path, method: :delete %></p>
</header>

<section class="groups-list-item">
  <img src="<%= @group.icon %>" alt="Category icon image">
  <h2><%= @group.name %></h2>
  <% total = 0.00 %>
  <% @group.group_entities.each {|group_entity| total += group_entity.entity.amount} %>
  <span class="amount">$<%= total %></span>
</section>

<% if @group_entities.empty? %>
  <h2 class="splash-welcome">There are not transactions yet!</h2>
  <p class="splash-text">Create a transaction for this category by clicking on the button below.</p>
<% else %>
  <ul>
    <% @group_entities.each do |group_entity| %>
      <li class="entities-list-item">
        <div class="entity-info">
          <h2><%= group_entity.entity.name %></h2>
          <p><%= group_entity.entity.created_at %></p>
        </div>
        <div class="entity-amount">
          <span>Amount:</span>
          <span class="amount">$<%= group_entity.entity.amount %></span>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>
<div class="button-container">
  <%= button_to 'New Transaction', new_entity_path, method: :get, class: 'second-button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.typekit.net/lrt1zlc.css">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<h1 class="splash-header">Paytrack</h1>
<div class="button-container">
  <% if user_signed_in? %>
    <h2 class="splash-welcome">Welcome, <%= current_user.name %></h2>
    <p class="splash-text">You are signed in.</p>
    <%= button_to 'Go to categories', groups_path, method: :get, class: 'main-button' %>
    <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'main-button' %>
  <% else %>
    <%= button_to 'Log in', user_session_path, class: 'main-button' %>
    <%= button_to 'Sign up', new_user_registration_path, method: :get, class: 'main-button' %>
  <% end %>
</div>